#colors
ccred=\033[0;31m
ccgreen=\033[0;32m
ccyellow=\033[0;33m
ccend=\033[0m

all: tests

tests:
	@echo "${ccgreen}Running tests${ccend}"
	@echo "${ccred}Tests MOCK${ccend}"
	@echo "${ccyellow}Tests passed${ccend}"